/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    {
      type: "category",
      label: "Basics",
      link: {type: "generated-index"},
      items: [
        "overview",
        "get-started",
        "how-it-works",
        "tutorials",
      ],
    },
    {
      type: "category",
      label: "Access Control Models",
      link: {type: "generated-index"},
      items: [
        "supported-models",
        "syntax-for-models",
        "effector",
        "function",
        {
          type: "category",
          label: "RBAC",
          link: {type: "doc", id: "rbac-overview"},
          items: [
            "rbac",
            "rbac-with-pattern",
            "rbac-with-domains",
            "rbac-with-conditions",
            "rbac-96",
          ],
        },
        "rebac",
        "abac",
        "pbac",
        {
          type: "category",
          label: "MAC",
          link: {type: "doc", id: "mac-overview"},
          items: [
            "blp",
            "biba",
            "lbac",
          ],
        },
        "orbac",
        "priority-model",
        "ucon",
        "superadmin",
      ],
    },
    {
      type: "category",
      label: "Storage",
      link: {type: "generated-index"},
      items: [
        "model-storage",
        "policy-storage",
        "policy-subset-loading",
      ],
    },
    {
      type: "category",
      label: "Use Cases",
      link: {type: "generated-index"},
      items: [
        "data-permissions",
        "menu-permissions",
      ],
    },
    {
      type: "category",
      label: "Plugins",
      link: {type: "doc", id: "plugins-overview"},
      items: [
        "enforcers",
        "adapters",
        "watchers",
        "dispatchers",
        "role-managers",
        {
          type: "category",
          label: "Middleware",
          link: {type: "doc", id: "middlewares"},
          items: [
            "kong-authz",
            "graphql-middlewares",
            "cloud-native",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "API",
      link: {type: "generated-index"},
      items: [
        "api-overview",
        "management-api",
        "rbac-api",
        "rbac-with-domains-api",
        "rbac-with-conditions-api",
        "rolemanager-api",
      ],
    },
    {
      type: "category",
      label: "Advanced Usage",
      link: {type: "generated-index"},
      items: [
        "multi-threading",
        "benchmark",
        "performance",
        "k8s-gatekeeper",
        "envoy",
      ],
    },
    {
      type: "category",
      label: "Management",
      link: {type: "generated-index"},
      items: [
        "admin-portal",
        "service",
        "command-line-tools",
        "log-error",
        "frontend",
      ],
    },
    {
      type: "category",
      label: "Editors & Tools",
      link: {type: "generated-index"},
      items: [
        "online-editor",
        "ide-plugins",
      ],
    },
    {
      type: "category",
      label: "About & More",
      link: {type: "generated-index"},
      items: [
        "adopters",
        "contributing",
        "privacy-policy",
        "terms-of-service",
      ],
    },
  ],
};
