/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    {
      type: "category",
      label: "The basics",
      link: {type: "generated-index"},
      items: [
        "basics/Overview",
        "basics/GetStarted",
        "basics/HowItWorks",
        "basics/Tutorial",
        "basics/UnderstandingCasbinMatchingInDetail",
        {
          type: "link",
          label: "PDF Download",
          href: "/pdf",
        },
      ],
    },
    {
      type: "category",
      label: "Model",
      link: {type: "generated-index"},
      items: [
        "model/SupportedModels",
        "model/SyntaxForModels",
        "model/Effector",
        "model/Function",
        "model/RBAC",
        "model/RBACWithPattern",
        "model/RBACWithDomains",
        "model/RBACWithConditions",
        "model/CasbinRBACAndRBAC96",
        "model/ReBAC",
        "model/ABAC",
        "model/BLP",
        "model/Biba",
        "model/LBAC",
        "model/PriorityModel",
        "model/SuperAdmin",
      ],
    },
    {
      type: "category",
      label: "Storage",
      link: {type: "generated-index"},
      items: [
        "storage/ModelStorage",
        "storage/PolicyStorage",
        "storage/PolicySubsetLoading",
      ],
    },
    {
      type: "category",
      label: "Scenarios",
      link: {type: "generated-index"},
      items: [
        "scenarios/DataPermissions",
        "scenarios/MenuPermissions",
      ],
    },
    {
      type: "category",
      label: "Extensions",
      link: {type: "generated-index"},
      items: [
        "extensions/Enforcers",
        "extensions/Adapters",
        "extensions/Watchers",
        "extensions/Dispatchers",
        "extensions/RoleManagers",
        "extensions/Middlewares",
        "extensions/GraphQLMiddlewares",
        "extensions/CloudNative",
      ],
    },
    {
      type: "category",
      label: "API",
      link: {type: "generated-index"},
      items: [
        "api/APIOverview",
        "api/ManagementAPI",
        "api/RBACAPI",
        "api/RBACWithDomainsAPI",
        "api/RBACWithConditionsAPI",
        "api/RoleManagerApi",
      ],
    },
    {
      type: "category",
      label: "Advanced usage",
      link: {type: "generated-index"},
      items: [
        "advanced/MultiThreading",
        "advanced/Benchmark",
        "advanced/Performance",
        "advanced/K8sAuthz",
        "advanced/K8sGateKeeper",
        "advanced/EnvoyAuthz",
      ],
    },
    {
      type: "category",
      label: "Management",
      link: {type: "generated-index"},
      items: [
        "management/AdminPortal",
        "management/Service",
        "management/CommandLineTools",
        "management/LogError",
        "management/FrontendUsage",
      ],
    },
    {
      type: "category",
      label: "Editor",
      link: {type: "generated-index"},
      items: [
        "editor/OnlineEditor",
        "editor/IDEPlugins",
      ],
    },
    {
      type: "category",
      label: "More",
      link: {type: "generated-index"},
      items: [
        "more/Adopters",
        "more/Contributing",
        "more/PrivacyPolicy",
        "more/TermsOfService",
        "more/RefundPolicy",
      ],
    },
  ],
};
